export const courses = [
    {
        id : "1",
        img : "./assets/image/courses/asp.jpg",
        time : "22 : 14 : 23",
        category : "web",
        name : "محمد اشرافی",
        title : "آموزش رایگان Asp.Net Core",
        price : "رایگان",
    },
    {
        id : "2",
        img : "./assets/image/courses/asp2.jpg",
        time : "20 : 28 : 11",
        category : "web",
        name : "سوگند قاسم پور",
        title : "دوره رایگان پروژه محور Asp.net MVC",
        price : "رایگان",
    },
    {
        id : "3",
        img : "./assets/image/courses/asp3.jpg",
        time : "78 : 01 : 16",
        category : "web",
        name : "محمد اشرافی",
        title : "اموزش پیشرفته Core",
        price : "900.000",
    },
    {
        id : "4",
        img : "./assets/image/courses/bootstrap.jpg",
        time : "06 : 24 : 55",
        category : "ui",
        name : "فرهاد اصلانی",
        title : "اشنایی با بوت استرپ",
        price : "رایگان",
    },
    {
        id : "5",
        img : "./assets/image/courses/c++.jpg",
        time : "20 : 13 : 47",
        category : "data",
        name : "علی خموش",
        title : "اموزش رایگانc++",
        price : "رایگان",
    },
    {
        id : "6",
        img : "./assets/image/courses/clean.jpg",
        time : "00 : 58 : 00",
        category : "web",
        name : "حسین عنایتی",
        title : "اشنایی با clean code",
        price : "رایگان",
    },
    {
        id : "7",
        img : "./assets/image/courses/cor.jpg",
        time : "07 : 09 : 17",
        category : "web",
        name : "محمد اشرافی",
        title : "اموزش جامع core",
        price : "200.000",
    },
    {
        id : "8",
        img : "./assets/image/courses/css.jpg",
        time : "04 : 01 : 00",
        category : "ui",
        name : "حسین عنایتی",
        title : "اموزش جامع css",
        price : "رایگان",
    },
    {
        id : "9",
        img : "./assets/image/courses/dart.jpg",
        time : "08 : 15 : 05",
        category : "mobile",
        name : "ساسان صفری",
        title : "آموزش رایگان مقدماتی تا پیشرفته زبان دارت (Dart)",
        price : "رایگان",
    },
    {
        id : "10",
        img : "./assets/image/courses/drf.jpg",
        time : "07 : 26 : 18",
        category : "web",
        name : "حسین امیری",
        title : "آموزش django rest framework",
        price : "200.000",
    },
    {
        id : "11",
        img : "./assets/image/courses/efcore.jpg",
        time : "07 : 09 : 17",
        category : "web",
        name : "محمد اشرافی",
        title : "آموزش جامع EF Core",
        price : "200.000",
    },
    {
        id : "12",
        img : "./assets/image/courses/flex.jpg",
        time : "02 : 59 : 00",
        category : "ui",
        name : "حسین عنایتی",
        title : "اموزش کامل flex-box",
        price : "رایگان",
    },
    {
        id : "13",
        img : "./assets/image/courses/flutter.jpg",
        time : "56 : 06 : 16",
        category : "mobile",
        name : "ساسان صفری",
        title : "اموزش ۰ تا ۱۰۰ فلاتر",
        price : "1,500,000",
    },
    {
        id : "14",
        img : "./assets/image/courses/iden.jpg",
        time : "04 : 47 : 48",
        category : "web",
        name : "محمد حسین فلاحی",
        title : "آموزش رایگان Identity در Asp.Net Core",
        price : "رایگان",
    },
    {
        id : "15",
        img : "./assets/image/courses/java.jpg",
        time : "16 : 18 : 08",
        category : "mobile",
        name : "حامد گنجعلی",
        title : "اموزش رایگان جاوا",
        price : "رایگان",
    },
    {
        id : "16",
        img : "./assets/image/courses/jquery.jpg",
        time : "08 : 37 : 12",
        category : "ui",
        name : "محمد هاشمی",
        title : "اموزش کامل jquery",
        price : "رایگان",
    },
    {
        id : "17",
        img : "./assets/image/courses/live.jpg",
        time : "06 : 20 : 29",
        category : "web",
        name : "قاسم بساکی",
        title : "آموزش رایگان ۰ تا ۱۰۰ livewire",
        price : "رایگان",
    },
    {
        id : "18",
        img : "./assets/image/courses/mat.jpg",
        time : "08 : 49 : 60",
        category : "ui",
        name : "قاسم بساکی",
        title : "آموزش طراحی وب با فریمورک materialize",
        price : "99.000",
    },
    {
        id : "19",
        img : "./assets/image/courses/mogo.jpg",
        time : "04 : 03 : 43",
        category : "data",
        name : "سروش کاردانی",
        title : "آموزش دیتابیس MongoDB از مقدماتی تا پیشرفته",
        price : "رایگان",
    },
    {
        id : "20",
        img : "./assets/image/courses/mvc.jpg",
        time : "19 : 26 : 50",
        category : "web",
        name : "سوگند قاسم پور",
        title : "دوره پیشرفته ASP.NET MVC (پروژه محور)",
        price : "100.000",
    },
    {
        id : "21",
        img : "./assets/image/courses/php2.jpg",
        time : "17 : 52 : 00",
        category : "web",
        name : "حسین عنایتی",
        title : "اموزش 0 تا 100 php",
        price : "رایگان",
    },
    {
        id : "22",
        img : "./assets/image/courses/react.jpg",
        time : "36 : 11 : 04",
        category : "mobile",
        name : "قاسم بساکی",
        title : "اموزش کامل react js",
        price : "900و000",
    },
    {
        id : "23",
        img : "./assets/image/courses/seo.jpg",
        time : "05 : 03 : 34",
        category : "web",
        name : "محمد رضا احمی",
        title : "آموزش رایگان مقدماتی سئو (S.E.O)",
        price : "رایگان",
    },
    {
        id : "24",
        img : "./assets/image/courses/singl.jpg",
        time : "06 : 58 : 47",
        category : "web",
        name : "محمد اشرافی",
        title : "آموزش رایگان SignalR",
        price : "رایگان",
    },
    {
        id : "25",
        img : "./assets/image/courses/requPyton.jpg",
        time : "00 : 59 : 38",
        category : "web",
        name : "امیر حسین امیری",
        title : "آموزش رایگان کتابخانه ی Requests در پایتون (python)",
        price : "رایگان",
    },
    {
        id : "26",
        img : "./assets/image/courses/solidity.jpg",
        time : "12 : 04 : 01",
        category : "web",
        name : "میلاد دهیامی",
        title : "اموزش سالیدیتی",
        price : "1.500.000",
    },
];