export const teachers = [
    {
        id : "1",
        name : "محمد هاشمی",
        email : "mohammadhg98@gmai...",
        img : "./assets/image/teachers/teach (1).jpg",
        courses : "6",
        followers : "155",
        path : "https://codeyad.com/Masters/Profile/mohammadHashemi",
    },
    {
        id : "2",
        name : "حسین عنایتی",
        email : "mr.h.enayati1380@...",
        img : "./assets/image/teachers/teach (6).jpg",
        courses : "11",
        followers : "272",
        path : "https://codeyad.com/Masters/Profile/mr.hosseinenayati",
    },
    {
        id : "3",
        name : "محمد اشرافی",
        email : "mohammad.ashrafi2...",
        img : "./assets/image/teachers/teach (5).jpg",
        courses : "7",
        followers : "87",
        path : "https://codeyad.com/Masters/Profile/mohammad-ashrafi",
    },
    {
        id : "4",
        name : "امیرحسین امیری",
        email : "amirhamiri74@gmai...",
        img : "./assets/image/teachers/teach (4).jpg",
        courses : "4",
        followers : "1033",
        path : "https://codeyad.com/Masters/Profile/amira",
    },
    {
        id : "5",
        name : "میلاد ده یامی",
        email : "m.dehyami@gmail.com",
        img : "./assets/image/teachers/teach (3).jpeg",
        courses : "4",
        followers : "483",
        path : "https://codeyad.com/Masters/Profile/miladdehyami",
    },
    {
        id : "6",
        name : "فرهاد اصلانی",
        email : "aslani172@gmail.com",
        img : "./assets/image/teachers/teach (2).jpeg",
        courses : "5",
        followers : "13",
        path : "https://codeyad.com/Masters/Profile/farhad_aslani",
    },
    {
        id : "7",
        name : "عرفان شریعتی",
        email : "erfansch5@gmail.com",
        img : "./assets/image/teachers/teach (3).jpg",
        courses : "0",
        followers : "1",
        path : "https://codeyad.com/Masters/Profile/erfan7",
    },
    {
        id : "8",
        name : "سوگند قاسم پور",
        email : "sogand.ghasempour...",
        img : "./assets/image/teachers/teach (1).jpeg",
        courses : "2",
        followers : "68",
        path : "https://codeyad.com/Masters/Profile/sogand.ghasempour",
    },
    {
        id : "9",
        name : "قاسم بساکی",
        email : "mahdicmptr@gmail.com",
        img : "./assets/image/teachers/teach (2).jpg",
        courses : "5",
        followers : "45",
        path : "https://codeyad.com/Masters/Profile/qasemb",
    },
]